<a href="https://colab.research.google.com/github/Vatsal-Savani-006/Machine-Learning-Lab-Repo/blob/main/Vatsal-%20Practical4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 2 way
# on independent function
# function given in library

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("burnoutminer/heights-and-weights-dataset")

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (0.4.3).
Downloading from https://www.kaggle.com/api/v1/datasets/download/burnoutminer/heights-and-weights-dataset?dataset_version_number=1...

100%|██████████| 244k/244k [00:00<00:00, 58.4MB/s]

Extracting files...

#Dataset Preparation

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv(path + "/SOCR-HeightWeight.csv")
df.head()

   Index  Height(Inches)  Weight(Pounds)
0      1        65.78331        112.9925
1      2        71.51521        136.4873
2      3        69.39874        153.0269
3      4        68.21660        142.3354
4      5        67.78781        144.2971

#Normal Equation

In [ ]:
from numpy import sign
def intercept_slop(x,y):
    n=len(x)
    sig_x=np.sum(x)
    sig_y=np.sum(y)
    sign_xy=np.sum(x*y)
    sig_x2=np.sum(x**2)
    m = (n*sign_xy-sig_x*sig_y)/(n*sig_x2-sig_x**2)
    c = (sig_y-m*sig_x)/n
    return m,c

m,c = intercept_slop(df["Height(Inches)"],df["Weight(Pounds)"])
print(m,c)

3.0834764454016637 -82.57574306445234

##Prediction

In [ ]:
def predict(x,m,c):
    y_pred=m*x+c
    y_pred=pd.Series(y_pred,name="Weight(Pounds)")
    return y_pred
y_pred=predict(df["Height(Inches)"],m,c)
y_pred.head()

0    120.265544
1    137.939722
2    131.413637
3    127.768536
4    126.446372
Name: Weight(Pounds), dtype: float64

##Mean Squared Error

In [ ]:
from sklearn.metrics import r2_score, mean_squared_error
y_org = df['Weight(Pounds)']
print('Mean Squared Error:', mean_squared_error(y_pred, y_org))

Mean Squared Error: 101.58853248632849

##Linear Regression Using sklearn

In [ ]:
from sklearn.linear_model import LinearRegression

from sklearn.metrics import r2_score, mean_squared_error
from sklearn.model_selection import train_test_split

##

In [ ]:
df[["Height(Inches)"]]
y = df["Weight(Pounds)"]

model = LinearRegression()

model.fit(X,y)

y_newpred = model.predict(df[["Height(Inches)"]])
print(y_newpred)
print("R2 Score:", r2_score(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))

[120.26554382 137.93972246 131.41363707 ... 116.92071191 125.64889284
 129.80674499]
R2 Score: 0.26059113512888576
MSE: 102.48790963792534

##Load The Dataset

In [ ]:
X = df[["Height(Inches)"]]
y = df["Weight(Pounds)"]

##Data Splitting and Model Training

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

##Prediction

In [ ]:
y_pred = model.predict(X_test)
y_pred

array([128.41144971, 126.79032375, 126.06117947, ..., 128.86141782,
       124.33022578, 135.00025306])

In [ ]:
y_newpred = model.predict(X)
print(y_newpred[:100])

R2 Score: 0.26059113512888576
MSE: 102.48790963792534
[120.29980025 137.90386951 131.40367159 127.77303001 126.45611087
 129.25103596 132.6423047  133.29549709 126.80881264 123.36812757
 122.46312381 125.95095249 128.03678854 124.39453765 127.96673344
 136.60285942 122.38115228 129.10186559 137.02893324 124.43943926
 126.59732671 129.80683917 113.22930283 128.40346448 125.96541805
 124.67733789 135.8373516  125.55479259 122.60538387 119.24842094
 131.78622587 120.39159976 126.54361064 135.07783271 138.79339421
 130.81211909 123.43360652 126.06028881 126.51507877 114.96209927
 128.87262786 118.45785176 132.20035254 127.00739935 120.90658612
 129.1731799  123.67070663 126.1823708  132.70105762 130.44983503
 132.98858758 125.05565385 134.07765106 130.49673294 119.07207005
 133.81684093 134.49773595 122.63532851 122.08379433 125.68581191
 122.51376864 130.17775343 128.04007477 124.07509746 135.72546614
 127.78196734 130.36067678 126.28172557 124.69895946 125.16563514
 118.72431298 135.83867223 133.01816367 115.69836884 127.86086762
 122.06198849 128.22189247 119.35874006 132.388712   126.26486444
 129.07158312 123.37331798 133.40836534 121.82058864 130.79937342
 130.59307789 125.15559217 133.53582201 133.79267023 127.80054837
 127.50497175 133.99524955 137.81882674 130.80794219 133.44396107
 134.96106397 121.84503575 113.05921729 123.32129109 129.83325188]

##Mean Squared Error

In [ ]:
from sklearn.metrics import mean_squared_error
print("Mean Squared Error:", mean_squared_error(y_pred, y_test))

Mean Squared Error: 102.48790963792534